kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: banco-dados
  namespace: entrega
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard