apiVersion: v1
kind: PersistentVolume
metadata:
  name: banco-dados-disco
  namespace: entrega
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/bancodados
    type: ""
  persistentVolumeReclaimPolicy: Retain
status:
  phase: Available